<?php
/**
 * @category    CleverSoft
 * @package     CleverBase
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
/** 
 * @var $block \Magento\Swatches\Block\Product\Renderer\Configurable 
 */ 
?>
<?php
$radom = $block->getRandom();
?>
<div class="swatch-opt-<?php /* @escapeNotVerified */ echo $block->getProduct()->getId().$radom ?>"></div>
<script>
    require(["jquery", "jquery/ui", "cleverSwatchRenderer"], function ($) {
        $('.swatch-opt-<?php /* @escapeNotVerified */ echo $block->getProduct()->getId().$radom ?>').cleverSwatchRenderer({
            selectorProduct: '.product-item-details',
            onlySwatches: true,
            enableControlLabel: false,
            numberToShow: <?php /* @escapeNotVerified */ echo $block->getNumberSwatchesPerProduct(); ?>,
            jsonConfig: <?php /* @escapeNotVerified */ echo $block->getJsonConfig(); ?>,
            jsonSwatchConfig: <?php /* @escapeNotVerified */ echo $block->getJsonSwatchConfig(); ?>,
            mediaCallback: '<?php /* @escapeNotVerified */ echo $block->getMediaCallback() ?>'
        });
    });
</script>
