<div class="contact">
   <div class="row">
      <div class="col-xs-12">
         <div class="row">
            <div class="col-sm-6 text_column">
               <h3><?php /* @escapeNotVerified */ echo __('Let’s Talk Together') ?></h3>
               <p><?php /* @escapeNotVerified */ echo __('You already know what we do. Now all you have to do is get in touch<br> with us. Give us a call, shoot us an email, or drop in for some<br> wonderfully brewed coffee.') ?></p>
            </div>
            <div class="col-sm-6 contact-maps padding-left-60"><iframe style="border: 0px; width: 100%;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.5133253018125!2d105.80814449999995!3d21.01213699999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135ab602de9caab%3A0x2defdd20ba3f2eac!2zMTY5IE5ndXnhu4VuIE5n4buNYyBWxaksIFRydW5nIEhvw6AsIEPhuqd1IEdp4bqleQ!5e0!3m2!1svi!2s!4v1395192834951" height="200" frameborder="0"></iframe> </div>
         </div>
      </div>
   </div>
   <div class="row">
      <div class="col-xs-12 col-sm-6 ">
         <h3><?php /* @escapeNotVerified */ echo __('Send A Message') ?></h3>
         <form class="contact-form"
          action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
          id="contact-form"
          method="post"
          data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
          data-mage-init='{"validation":{}}'>
           
            <p><input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/></p>
            <p><input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/></p>
            <p><input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="" class="input-text" type="text" /></p>
            <p><textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea></p>   
            <?php echo $block->getChildHtml('form.additional.info'); ?>
            <div class="form-actions">
               <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="btn-novetty btn-raised primary">
                    <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
                </button>		
            </div>
         </form>
      </div>
      <div class="col-xs-12 col-sm-6 padding-left-60 hidden-xs">
         <div class="contact-title"> 
                <h3><?php /* @escapeNotVerified */ echo __('Our Address') ?></h3>
         </div>
         <div class="contact-address-block">
            <div class="contact-address">
               <div class="media">
                  <div class="pull-left">
                     <i class="fa fa-home"></i>
                  </div>
                  <div class="media-body">
                     <span class="contact-street">
                     <span class="s-name"><?php /* @escapeNotVerified */ echo __('Address') ?></span>
                         <?php /* @escapeNotVerified */ echo __('169 Building, Cau Giay District, Hanoi, Vietnam') ?>						</span>
                  </div>
               </div>
            </div>
            <div class="contact-contactinfo">
               <div class="media">
                  <div class="pull-left">
                     <i class="fa fa-phone"></i>
                  </div>
                  <div class="media-body contact-telephone"> 
                     <p class="s-phone"><?php /* @escapeNotVerified */ echo __('+84 435.551.571') ?></p>
                  </div>
               </div>
               <div class="media">
                  <div class="pull-left">
                     <i class="fa fa-mobile-phone"></i>
                  </div>
                  <div class="media-body contact-mobile">
                     <p class="s-phone"><?php /* @escapeNotVerified */ echo __('+84 435.551.571') ?></p>
                  </div>
               </div>
               <div class="media">
                  <div class="pull-left">
                     <i class="fa fa-envelope"></i>
                  </div>
                  <div class="media-body contact-emailto"> 
                     <p><a href="mailto:hello@apl.vn"><?php /* @escapeNotVerified */ echo __('hello@apl.vn') ?></a></p>
                  </div>
               </div>
            </div>
         </div>
         <div class="hours">
            <h3><?php /* @escapeNotVerified */ echo __('Opening Hourse') ?></h3>
            <p class="monday hss">
                <?php /* @escapeNotVerified */ echo __('Monday to Friday: 10 am - 9 pm') ?>
            </p>
            <p class="saday hss">
                <?php /* @escapeNotVerified */ echo __('Saturday &amp; Sunday: 10 am - 11 pm') ?>
            </p>
         </div>
      </div>
   </div>
</div>
