<?php
/**
 * @category    CleverSoft
 * @package     CleverMegaMenus
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
 ?>
<div style="min-height: 20px"></div>
<div class="row zoo-menu-content">

	<div id="menu-spinner" data-role="spinner" class="admin__data-grid-loading-mask">
        <div class="spinner">
            <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
        </div>
    </div>

    <div class="col-m-3 col-left">
        <div class="menu-item-types">
            <div class="type-items" id="type-items"></div>
        </div>
    </div>
    <div class="col-m-9 col-main">
        <div class="menu-item-wrapper">
            <h2 class="title"><?php echo __('MegaMenu Structure') ?></h2>
			<span id="text_change_edit"></span>

            <div class="menu" id="menu-to-edit">
            	
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
require([
	"jquery",
	"Magento_Ui/js/modal/alert",
	"Magento_Ui/js/modal/modal",
	"Magento_Ui/js/modal/confirm",
	"jqueryTmpl",
	"cleverJqueryUi",
	"categoryChooser",
	"wysiwygEditor",
	"menuLayout",
	"domReady!"
],function($,alert,modal,confirm){
	$(function () {
		$( "#editting-tabs" ).tabs();
        $(document).live('cleverMoreOptionsParentMenu',function(event){
            var a = event.target;
            var b = event.target.nodeName;
        });
	});
	window.cleverInstantiateChooser = function(uniqId) {
		window[uniqId] = new WysiwygWidget.categoryChooser(
			uniqId,
			"<?php echo $this->getUrl('catalog/category_widget/chooser') ?>uniq_id/"+uniqId,
			{"buttons":{"open":"<?php echo __('Select Category...') ?>","close":"<?php echo __('Close') ?>"}}
		);
		if ($(uniqId+"value")){
			$(uniqId+"value").advaiceContainer = uniqId+"advice-container";
		}
	};
	var $menu = $('#menu-to-edit');
	$menu.menuLayout({
		menuItemTypes: menuItemTypes,
		menuItems: menuItems,
		previewUrl: '<?php echo $this->getUrl('megamenu/menuview/view') ?>',
		previewBtn: '',
		previewForm: '#edit_form',
		alert: alert,
		confirm: confirm,
		mediaUrl: '<?php echo $this->getMediaUrl() ?>',
		imagePlaceholder: '<?php echo $this->getImageUrl('menu/placeholder.jpg') ?>',
		spinner: '#menu-spinner'
	});
});
</script>