<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post info template
 *
 * @var $block \Magefan\Blog\Block\Post\Info
 */
?>

<?php $_post = $block->getPost() ?>

<div class="post-info clear">
    <?php echo $_post->getPublishDate('F d, Y') ?>
    <?php if ($block->authorEnabled()) { ?>
        <?php if ($_author = $_post->getAuthor()) { ?>
            <div class="item post-author">
                <span class="label"><?php echo __('Author:') ?></span>
            <span class="value">
                <?php if ($authorPageEnabled = $block->authorPageEnabled()) { ?>
                <a title="<?php echo $block->escapeHtml($_author->getTitle()) ?>" href="<?php echo $_author->getAuthorUrl() ?>">
                    <?php } ?>
                    <?php echo $block->escapeHtml($_author->getTitle()) ?>
                    <?php if ($authorPageEnabled) { ?>
                </a>
            <?php } ?>
            </span>
            </div>
        <?php } ?>
    <?php } ?>
</div>