<?php
/**
 * @category    CleverSoft
 * @package     CleverProduct
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
?>
<?php
/* @var $this CleverSoft CleverProduct Block_Widget */
use Magento\Framework\App\Action\Action;
$_id = $block->getConfig('id')?$block->getConfig('id'):$block->getData('id');
$_title = $block->getConfig('widget_title') ? $block->getConfig('widget_title') : $block->getData('widget_title');
$t = microtime();
$tab = $block->getData('tab');
?>
<div class="<?php echo $block->getData('classes') ?> zoo-product-collection02" id="<?php echo $_id ?>">
    <?php if ($_title): ?>
        <div class="zoo-main-heading">
            <div class="zoo-heading-wrapper-title">
                <h3><span><?php echo $_title ?></span></h3>
            </div>
        </div>
    <?php endif ;
    $_matoHelper = $this->helper('CleverSoft\Base\Helper\Data');
    ?>
    <?php if ($exist = ($block->getData('collection') && $block->getData('collection')->getSize())): ?>
        <?php
        $type = 'widget-product-grid';

        $mode = 'grid';

        $count = $block->getData('collection') ? $block->getData('collection')->count() : 0;
        //        $carousel = $block->getData('carousel');

        $row = (int)$block->getData('limit');
        $column = 1;

        $image = 'new_products_content_widget_grid';
        $items = $block->getData('collection')->getItems();

        $showWishlist = true;
        $showCompare = true;
        $showCart = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $_imageHelper = $this->helper('CleverSoft\Base\Helper\Image');
        $description = false;
        $theme = $this->helper('CleverSoft\Base\Helper\Data');
        $imgWidth = $block->getData('image_width') ;
        $imgHeight = $block->getData('image_height') ;
        //Get icon lazy load
        $lazyhelper = $this->helper('CleverSoft\Base\Helper\Data');
        $lazyload = $block->getData('lazyload');
        if (is_null($lazyload) ) $lazyload = false;
        //End get Icon lazy load
        //Image aspect ratio settings
        $keepAspectRatio = $block->getData('aspect_ratio');
        if (is_null($keepAspectRatio)) $keepAspectRatio = false;
        if ($keepAspectRatio)  {
            $imgHeight = 0; //Height will be calculated automatically (based on width) to keep the aspect ratio
            $catViewKeepFrame = FALSE;
        }  else {
            $catViewKeepFrame = TRUE;
        }

        $extClass = '';
        ?>
        <div class="block widget zoo-block-products-list <?php /* @escapeNotVerified */
        echo $mode; ?>">
            <div class="block-content">
                <?php $i = 0;
                foreach ($items as $_item): ?>
                <?php /* @escapeNotVerified */
                echo '<!-- ' . $image . '-->' ?>
                <?php if (($row > 1 && $i % $row == 0)): ?>
                <div class="products-<?php /* @escapeNotVerified */
                echo $mode; ?> <?php /* @escapeNotVerified */
                echo $mode; ?>">
                    <ol class="product-items vertical-carousel <?php /* @escapeNotVerified */
                    echo $type; ?>">
                        <?php endif ?>

                        <?php $i++ ?>
                        <?php /* @escapeNotVerified */
                        echo ($i == 1) ? '<li class="'. $extClass .'">' : '</li><li class="' . $extClass .'">';
                        ?>
                        <div class="product-item-info">
                            <div class="zoo-inner-product-item-info slider">
                                <a href="<?php /* @escapeNotVerified */
                                echo $block->getProductUrl($_item) ?>" class="product-item-photo" style="width: <?php echo $block->getData('product_im_w') ?>!important;">
                                    <?php echo $theme->getLabel($_item); ?>
                                    <?php if(!$imgWidth) : ?>
                                        <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                    <?php
                                    ////this else is for full width image - Hạnh issue
                                    else: ?>
                                        <img id="product-collection-image-<?php echo $_item->getId(); ?>"
                                             class="lazy img-lazyload"
                                             src="<?php if($lazyload) echo $block->getViewFileUrl('CleverSoft_Base::images/transparent.gif'); else echo $_imageHelper->getImg($_item, $imgWidth, $imgHeight,'category_page_grid'); ?>"
                                             data-src="<?php echo $_imageHelper->getImg($_item, $imgWidth, $imgHeight,'category_page_grid'); ?>"
                                             alt="<?php echo $block->stripTags($_item->getName(), null, true) ?>" />
                                    <?php endif; ?>
                                    <?php if (!$theme->getCfg('category/alt_image')): ?>
                                        <span class="product-img-additional alt-image">
                                        <?php $a = $theme->getAltImgHtml($_item, $imgWidth, $imgHeight, $image); ?>
                                        <?php echo $theme->getAltImgHtml($_item, $imgWidth, $imgHeight, $image); ?>
                                    </span>
                                    <?php endif; ?>
                                </a>
                                <div class="product details product-item-details">
                                    <strong class="product-item-name">
                                        <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                           href="<?php /* @escapeNotVerified */
                                           echo $block->getProductUrl($_item) ?>"
                                           class="product-item-link">
                                            <?php echo $block->escapeHtml($_item->getName()) ?>

                                        </a>
                                    </strong>
                                    <?php
                                    echo $block->getProductPriceHtml($_item, \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE);
                                    ?>

                                    <?php if ($templateType): ?>
                                        <?php echo $block->getReviewsSummaryHtml($_item, $templateType,true) ?>
                                    <?php endif; ?>
                                    <?php echo $block->getColorSwatchDetailsHtml($_item); ?>

                                </div>
                            </div>
                        </div>
                        <?php echo ($i == count($items)) ? '</li>' : '' ?>
                        <?php if ($i == $count || ($row > 1 && $i % $row == 0)): ?>
                        <!--                --><?php //if ($i == $count || $i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
                    </ol>
                </div>
            <?php endif ?>
                <?php if ($i == $count): ?>
            </div>
            <?php endif ?>
            <?php endforeach ?>
        </div>
    <?php endif; ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
</div>
<script>
    require([
        "CleverSoft_CleverProduct/js/frontend",
        "prototype"
    ], function (MTWidget) {
        $(function() {
            new MTWidget('<?php echo $_id ?>', {
                animation: <?php echo $block->getData('animation') ?>,
                parallax: <?php echo $block->getData('parallax') ?>,
//            carousel: <?php //echo $block->getConfig('carousel') ?>//,
                countdown: <?php echo $block->getData('countdown') ?>,
//            carouselConfig: {
//
//            },
                countdownConfig: {
                    dayText: '',
                    hourText: '',
                    minText: '',
                    secText: '',
                    daySingularText: '',
                    hourSingularText: '',
                    minSingularText: '',
                    secSingularText: ''
                },
                countdownTemplate: '<div class="day"><span class="no">%d</span><span class="text">days</span></div><div class="hours"><span class="no">%h</span><span class="text">hours</span></div><div class="min"><span class="no">%i</span><span class="text">minutes</span></div><div class="second"><span class="no">%s</span><span class="text">seconds</span></div>',
            });
        });
    });

    require(["jquery","js/jquery.noconflict", "CleverSoft_CleverProduct/js/jquery.bxslider"], (function ($) {
            $(document).ready(function () {
                jQuery(".product-item-info img.img-lazyload").css('height','<?php echo $imgWidth; ?>');
                $(".home-05 .page-wrapper .top-rated.home05 .block.widget.zoo-block-products-list.grid .block-content").css("overflow", "visible");
                var page = 0;
                var maxSlides = 3;
                var slider = $('ol.vertical-carousel').bxSlider({
                    mode: 'vertical',
                    minSlides: 3,
                    maxSlides: maxSlides,
                    auto: <?php echo  $this->getData('vautoplay'); ?>,
                    pause: <?php echo $this->getData('vautoplaytimeout'); ?>,
                    startSlide: page,
                    autoHover: <?php echo $this->getData('vautoplayhoverpause'); ?>,
                    nextText: "<span class='cs-font clever-icon-next'></span>",
                    prevText: "<span class='cs-font clever-icon-prev'></span>",
                    pager: <?php echo $this->getData('venable_bullet'); ?>,
                    <?php if($lazyload): ?>
                    onSliderLoad: function () {
                        var $sliderImgs = $(".slider img");
                        var start = page * maxSlides + maxSlides;
                        var stop = start + maxSlides;
                        for (var i = start; i < stop; i++) {
                            var selecter = '[data-src="' + $sliderImgs.eq(i).data('src') + '"]';
                            $(selecter).attr('src', $(selecter).data('src')).one('load', function () {
                                $(this).removeClass('lazy');
                            });
                        }
                    },
                    onSlideAfter: function () {
                        page = slider.getCurrentSlide();
                        var $sliderImgs = $(".slider img");
                        var start = page * maxSlides + maxSlides;
                        var stop = start + maxSlides;
                        for (var i = start; i < stop; i++) {
                            var selecter = '[data-src="' + $sliderImgs.eq(i).data('src') + '"]';
                            $(selecter).attr('src', $(selecter).data('src')).one('load', function () {
                                $(this).removeClass('lazy');
                            });
                        }
                    }
                    <?php endif; ?>
                });
            });
        })
    );
</script>
