<?php
/**
 * @category    CleverSoft
 * @package     CleverProduct
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
?>
<?php
use Magento\Framework\App\Action\Action;
/* @var $this CleverSoft CleverProduct_Block_Widget */
$_matoHelper = $this->helper('CleverSoft\Base\Helper\Data');
$_id = $block->getConfig('id')?$block->getConfig('id'):$block->getData('id');
$_title = $block->getConfig('widget_title') ? $block->getConfig('widget_title') : $block->getData('widget_title');
$_columnCount = $block->getData('product_m_w');
$tab = $block->getData('tab');
$lazyload = $block->getData('lazyload');
if (is_null($lazyload)) $lazyload = false;
$min_height_img_lazyload = $block->getData('height_image');
$t = microtime();
?>
<div class="<?php echo $block->getData('classes') ?> zoo-product-collection01 ajax-img-product-attribute products wrapper grid" id="<?php echo $_id ?>">
    <?php if ($_title): ?>
        <div class="zoo-main-heading">
            <div class="zoo-heading-wrapper-title">
                <h3><span><?php echo $_title ?></span></h3>
            </div>
        </div>
    <?php endif ?>
    <?php if ($exist = ($block->getData('collection') && $block->getData('collection')->getSize())): ?>
        <?php
        $viewMode = 'grid';
        $type = 'widget-product-grid';

        $count = $block->getData('collection') ? $block->getData('collection')->count() : 0;
        $carousel = $block->getData('carousel');

        $row = $block->getData('row');
        $column = $carousel == 1 && $row == 1 ? $count : ($carousel == 1 && $row > 1 ? $row : $block->getData('column'));

        $image = 'new_products_content_widget_grid';
        $items = $block->getData('collection')->getItems();

        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $description = false;
        $theme = $this->helper('CleverSoft\Base\Helper\Data');
        $_imageHelper = $this->helper('CleverSoft\Base\Helper\Image');
        $_helper = $this->helper('Magento\Catalog\Helper\Output');



        $imgWidth = $block->getData('image_width');
        $imgHeight = $block->getData('image_height');


        $showWishlist = $theme->getCfg('category_grid/display_addtowishlist');
        $showCompare = $theme->getCfg('category_grid/display_addtocompare');
        $showCart = $theme->getCfg('category_grid/display_addtocart');
        $showSize = $theme->getCfg('category_grid/display_size');
        $showPrice = $theme->getCfg('category_grid/display_price');
        $showColor = $theme->getCfg('category_grid/display_color');
        $showRating = $theme->getCfg('category_grid/display_rating');
        $showProductName = $theme->getCfg('category_grid/display_productname');
        $addtolinks_position = $theme->getCfg('category_grid/addtolinks_position');
        $_columnCount = $block->getData('product_m_w');

        $containerClasses = "{$viewMode} products-{$viewMode} products-grid-partitioned category-products-grid";
        $itemgridClasses = 'itemgrid zoo-itemgrid-adaptive';

        // Get number of columns (from parameter or from theme config)
        $columnCount = $_matoHelper->getCfg('category_grid/column_count');
        if(!isset($columnCount) || empty($columnCount) || !$columnCount) $columnCount = 3;
        $itemgridClasses .= " zoo-grid-{$columnCount}col";

        if ($_matoHelper->getCfg('category_grid/display_name_single_line'))
            $containerClasses .= ' zoo-single-line-name';
        if ($_matoHelper->getCfg('category_grid/hover_effect'))
            $containerClasses .= ' hover-effect';
        if ($_matoHelper->getCfg('category_grid/centered'))
            $containerClasses .= ' centered';
        if ($_matoHelper->getCfg('category_grid/enable_border_boxshadow'))
            $containerClasses .= ' enable_border_boxshadow';
        if ($_matoHelper->getCfg('category_grid/disable_border_radius'))
            $containerClasses .= ' disable_border_radius';

        //Image aspect ratio settings
        $keepAspectRatio = $block->getData('aspect_ratio');
        if(is_null($keepAspectRatio)) $keepAspectRatio = false;

        if ($keepAspectRatio)
        {
            $imgHeight = 0; //Height will be calculated automatically (based on width) to keep the aspect ratio
            $catViewKeepFrame = FALSE;
        }
        else
        {
            $catViewKeepFrame = TRUE;
        }
        ?>
        <div class="<?php /* @escapeNotVerified */  echo $containerClasses; ?>">
        <ol class="clearfix items product-items itemgrid <?php /* @escapeNotVerified */
        echo $type; ?>  <?php if ($itemgridClasses) echo $itemgridClasses; ?>">
            <?php $i = 0;
            foreach ($items as $_item): ?>
                <?php /* @escapeNotVerified */
                echo '<!-- ' . $image . '-->' ?>
                <?php $i++ ?>
                <?php /* @escapeNotVerified */
                if ($_item->getIsSalable()) $product_stock = 'product-instock'; else $product_stock = 'product-oustock';
                ?>
                <li class="product-item product_hover <?php echo $product_stock ?>">
                    <div
                        class="product-item-info <?php if ($alternative_img = $theme->getAltImgHtml($_item, $imgWidth, $imgHeight, $image)): ?> have-alternative-image <?php endif; ?>"
                        data-container="product-grid">
                        <div class="zoo-inner-product-item-info">
                            <div class="zoo-product-image">
                                <?php if ($_item->getIsSalable()): echo $_matoHelper->getLabel($_item); ?>
                                <?php else : ?>
                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                            echo __('Out of stock') ?></span></div>
                                <?php endif; ?>
                                <?php if ($addtolinks_position == 1): ?>
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist != 'remove'): ?>
                                        <div class="zoo-wishlist <?php echo 'product_'.$showWishlist.'_item'; ?>" data-role="add-to-links">
                                            <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                               data-action="add-to-wishlist"    title="">
                                                <i class="fa fa-heart-o"></i>
                                                <span class="tooltip"><?php /* @escapeNotVerified */     echo __('Add to wishlist') ?></span>
                                            </a>
                                        </div>
                                    <?php endif; ?>
                                    <?php if ($block->getAddToCompareUrl() && $showCompare != 'remove'): ?>
                                        <div class="zoo-compare <?php echo 'product_'.$showCompare.'_item'; ?>" data-role="add-to-links">
                                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                            <a href="#" class="action tocompare"  data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item); ?>' >
                                                <span class="cs-font clever-icon-compare-6"></span>
                                                <span class="tooltip"><?php /* @escapeNotVerified */     echo __('Add to Compare') ?></span>
                                            </a>
                                        </div>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <a href="<?php /* @escapeNotVerified */
                                echo $block->getProductUrl($_item) ?>" class="product-item-photo" <?php if ($lazyload) echo 'style="min-height: '.$min_height_img_lazyload.'px"'?>>

                                    <?php if (!$imgWidth) : ?>
                                        <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                    <?php else: ?>
                                        <img id="product-collection-image-<?php echo $_item->getId(); ?>"
                                            <?php if($lazyload): ?>
                                                class="clazyload"  data-src="<?php echo $_imageHelper->getImg($_item, $imgWidth, $imgHeight, 'category_page_grid'); ?>"
                                                src="<?php echo $block->getViewFileUrl('CleverSoft_Base::images/transparent.gif'); ?>"  width="auto" height="auto"
                                            <?php else: ?>
                                                src="<?php echo $_imageHelper->getImg($_item, $imgWidth, $imgHeight, 'category_page_grid'); ?>"
                                            <?php endif; ?>
                                             alt="<?php echo $block->stripTags($_item->getName(), null, true) ?>"/>
                                    <?php endif; ?>
                                    <?php if ($theme->getCfg('category/alt_image')): ?>
                                        <span class="product-img-additional alt-image">
                                 <?php echo $alternative_img; ?>
                            </span>
                                    <?php endif; ?>
                                </a>

                                <div class="options-slideup">
                                    <div class="zoo-quickview">
                                <span rel="tooltip" data-placement="top"
                                      class="btn-cart zoo-tooltip show-quickview"
                                      data-id="<?php echo $_item->getId(); ?>">
                                 <?php echo __('Quick view') ?></span>
                                        <a class="product-quickview"
                                           href="<?php echo $block->getUrl('quickview/product/view/id/' . $_item->getId()); ?>"
                                           data-id='quickview-<?php echo $_item->getId() ?>'
                                           style='display:none'><?php echo __('Quick view') ?></a>
                                    </div>
                                </div>
                                <div class="product-date"
                                     data-date="<?php echo $this->helper('CleverSoft\CleverProduct\Helper\Data')->getDate($_item) ?>"></div>
                            </div>

                            <div class="product details product-item-details">
                                <?php if ($showProductName != 'remove'): ?>
                                    <h5 class="product-item-name <?php echo 'product_'.$showProductName.'_item'; ?>">
                                        <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                           href="<?php /* @escapeNotVerified */
                                           echo $block->getProductUrl($_item) ?>"
                                           class="product-item-link">
                                            <?php echo $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </h5>
                                <?php endif; ?>

                                <?php if ($templateType && $showRating != 'remove'): ?>
                                    <div class="<?php echo 'product_'.$showRating.'_item'; ?>">
                                        <?php echo $block->getReviewsSummaryHtml($_item, $templateType, true) ?>
                                    </div>
                                <?php endif; ?>

                                <?php if ($showPrice != 'remove'): ?>
                                    <div class="<?php echo 'product_'.$showPrice.'_item'; ?>">
                                        <?php echo $block->getProductPriceHtml($_item, \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE); ?>
                                    </div>
                                <?php endif; ?>

                                <?php if ($showColor != 'remove'): ?>
                                    <div class="<?php echo 'product_'.$showColor.'_item'; ?>">
                                        <?php echo $block->getColorSwatchDetailsHtml($_item); ?>
                                    </div>
                                <?php endif; ?>


                                <div class="hover-area text-center">
                                    <?php if ($showCart != 'remove'): ?>
                                        <div class="actions-primary <?php echo 'product_'.$showCart.'_item'; ?>">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                    <button class="action tocart"
                                                            data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */
                                                            echo $block->getAddToCartUrl($_item) ?>"}}'
                                                            type="button">
                                                        <?php /* @escapeNotVerified */
                                                        echo __('Add to Cart') ?>
                                                    </button>
                                                <?php else: ?>
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                        <form data-role="tocart-form"
                                                              action="<?php /* @escapeNotVerified */
                                                              echo $postParams['action']; ?>" method="post">
                                                            <input type="hidden" name="product"
                                                                   value="<?php /* @escapeNotVerified */
                                                                   echo $postParams['data']['product']; ?>">
                                                            <input type="hidden"
                                                                   name="<?php /* @escapeNotVerified */
                                                                   echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                                   value="<?php /* @escapeNotVerified */
                                                                   echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                            <?php echo $block->getBlockHtml('formkey') ?>
                                                            <button type="submit"
                                                                    class="action tocart">
											<span><?php /* @escapeNotVerified */
                                                echo __('Add to Cart') ?></span>
                                                            </button>
                                                        </form>
                                                    <?php else: ?>
                                                        <?php if ($_item->getIsSalable()): ?>
                                                            <div class="stock available">
											<span><?php /* @escapeNotVerified */
                                                echo __('In stock') ?></span></div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable">
											<span><?php /* @escapeNotVerified */
                                                echo __('Out of stock') ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            <?php endif; ?>

                                            <?php if ($addtolinks_position == 0): ?>
                                                <div class="add-to-links">
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist != 'remove'): ?>
                                                        <div class="<?php echo 'product_'.$showWishlist.'_item'; ?>" data-role="add-to-links">
                                                            <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                               data-action="add-to-wishlist"    title="">
                                                                <i class="fa fa-heart-o"></i>
                                                                <span class="add-to-label"><?php /* @escapeNotVerified */     echo __('Wishlist') ?></span>
                                                            </a>
                                                        </div>
                                                    <?php endif; ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare != 'remove'): ?>
                                                        <div class="<?php echo 'product_'.$showCompare.'_item'; ?>" data-role="add-to-links">
                                                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                            <a href="#" class="action tocompare"  data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item); ?>' >
                                                                <span class="cs-font clever-icon-compare-6"></span>
                                                                <span class="add-to-label"><?php /* @escapeNotVerified */     echo __('Compare') ?></span>
                                                            </a>
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endforeach ?>
        </ol>
        </div>
    <?php endif; ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }


    </script>
    <?php endif; ?>
    <script>
        require([
            "jquery"
        ],function($){
            $(window).load(function () {
                window.gridLayout = function(id = null){
                    id = id ? id : '<?php echo $_id; ?>';
                    $('#'+id).attr('data-mage-init', JSON.stringify({'equalHeight': {'target': ' .product-item'}}));
                    $('#'+id).trigger('contentUpdated');
                }
            });
        });
    </script>
</div>

<script>
    require([
        "CleverSoft_CleverProduct/js/frontend",
        "prototype"
    ], function (MTWidget) {
        $(function() {
            new MTWidget('<?php echo $_id ?>', {
                animation: <?php echo $block->getData('animation') ?>,
                parallax: <?php echo $block->getData('parallax') ?>,
                countdown: <?php echo $block->getData('countdown') ?>,
                countdownConfig: {
                    dayText: '',
                    hourText: '',
                    minText: '',
                    secText: '',
                    daySingularText: '',
                    hourSingularText: '',
                    minSingularText: '',
                    secSingularText: ''
                },
                countdownTemplate: '<div class="day"><span class="no">%d</span><span class="text">days</span></div><div class="hours"><span class="no">%h</span><span class="text">hours</span></div><div class="min"><span class="no">%i</span><span class="text">minutes</span></div><div class="second"><span class="no">%s</span><span class="text">seconds</span></div>',
            });
        });
    });
</script>
<?php if($this->helper('CleverSoft\Base\Helper\Data')->getCfg('category_grid/equal_height')): ?>
    <script type="text/x-magento-init">
    {
        "#<?php echo $_id ?>": {
            "equalHeight": {
                "target": " .product-item"
            }
        }
    }
</script>
<?php endif;?>
