<?php
/**
 * @category    CleverSoft
 * @package     CleverProduct
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */

use Magento\Framework\App\Action\Action;
$_matoHelper = $this->helper('CleverSoft\Base\Helper\Data');
$lazyload = $block->getData('lazyload');
if(is_null($lazyload)) $lazyload = false;

?>
<?php if ($exist = ($block->getData('collection') && $block->getData('collection')->getSize())):?>

    <?php
    $productCollection  = $block->getData('collection');
    $image = 'new_products_content_widget_grid';
    $type = 'widget-product-grid';
    $viewMode = 'grid';
    $showWishlist = true;
    $_imageHelper = $this->helper('CleverSoft\Base\Helper\Image');
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $theme = $this->helper('CleverSoft\Base\Helper\Data');
    $description = false;
    $items =        $productCollection->getItems();
    $count              = $productCollection ? $productCollection->count() : 0;
    $carousel           = $block->getData('carousel');
    $row                = $block->getData('row');
    $column             = $carousel == 1 && $row == 1 ? $count : ($carousel == 1 && $row > 1 ? $row : $block->getData('column'));
    $l_type = $block->getData('layout');
    $product_m_w = $block->getData('product_m_w');

    $imgWidth = $block->getData('image_width') ;
    $imgHeight = $block->getData('image_height') ;

    //Image aspect ratio settings
    $keepAspectRatio = $block->getData('aspect_ratio');
    if (is_null($keepAspectRatio)) $keepAspectRatio = false;
    if ($keepAspectRatio)  {
        $imgHeight = 0; //Height will be calculated automatically (based on width) to keep the aspect ratio
        $catViewKeepFrame = FALSE;
    }  else {
        $catViewKeepFrame = TRUE;
    }
    switch ($l_type) {
        case 'carousel':
            $row = 1;
            $carousel = 1;
            break;
        case 'list':
            $carousel = 0;
            $row = $block->getData('limit');
            $column = 1;
            break;
        case 'grid' :
            $carousel=0;
            break;
    }
    ?>
    <?php if ($l_type != 'grid') { ?>
        <div class="block widget zoo-block-products-list <?php /* @escapeNotVerified */ echo $viewMode; ?>">
            <div class="block-content">
                <?php $i = 0; foreach ($items as $_item): ?>
                    <?php $alternative_img = $theme->getAltImgHtml($_item, $imgWidth, $imgHeight, $image); ?>
                    <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                    <?php if ($i == 0): ?>
                        <div class="products-<?php /* @escapeNotVerified */ echo $viewMode; ?> <?php /* @escapeNotVerified */ echo $viewMode; ?>">
                        <ol class="product-items <?php /* @escapeNotVerified */ echo $type; ?> <?php echo $carousel && $row == 1 ? ' owl-carousel' : '' ?>">
                    <?php endif ?>

                    <?php $i++ ?>
                    <?php /* @escapeNotVerified */
                    if($carousel == 1) echo ($i == 1) ? '<li>' : '</li><li>';
                    else echo ($i == 1) ? '<li>' : '</li><li>';
                    ?>
                    <div class="product-item-info">
                        <div class="zoo-inner-product-item-info">
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a href="<?php /* @escapeNotVerified */
                                    echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                        <?php if (!$imgWidth) : ?>
                                            <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                        <?php else: ?>
                                            <img id="product-collection-image-<?php echo $_item->getId(); ?>"
                                                 class="clazyload"
                                                <?php if($lazyload): ?>
                                                    data-src="<?php echo $_imageHelper->getImg($_item, $imgWidth, $imgHeight, 'category_page_grid'); ?>"
                                                <?php else: ?>
                                                    src="<?php echo $_imageHelper->getImg($_item, $imgWidth, $imgHeight, 'category_page_grid'); ?>"
                                                <?php endif; ?>
                                                 alt="<?php echo $block->stripTags($_item->getName(), null, true) ?>"/>
                                        <?php endif; ?>
                                        <?php if ($theme->getCfg('category/alt_image')): ?>
                                            <span class="product-img-additional alt-image">
                                 <?php echo $alternative_img; ?>
                            </span>
                                        <?php endif; ?>
                                    </a>
                                </strong>
                                <?php
                                echo $block->getProductPriceHtml($_item,  \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE);
                                ?>

                                <?php if ($templateType): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart primary"
                                                                data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php
                                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                       class="action towishlist" data-action="add-to-wishlist"
                                                       title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                    <a href="#" class="action tocompare"
                                                       data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                                       title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                    <?php echo($i == count($items)) ? '</li>' : '' ?>
                    <?php if ($i == $count): ?>
                        </ol>
                        </div>
                    <?php endif ?>
                <?php endforeach ?>
            </div>
        </div>
    <?php } else {
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $description = false;
        $_helper = $this->helper('Magento\Catalog\Helper\Output');
        $id = $block->getConfig('id') ? $block->getConfig('id') : $block->getData('id');
        $block_id = $this->getLayout()->createBlock('CleverSoft\CleverProduct\Block\Widget');
        $_id = $block_id->getConfig('id');
//        $_id = $this->_mathRandom->getUniqueHash('widget-');
        $imgWidth = $theme->getCfg('category/image_width') ? $theme->getCfg('category/image_width') : '';
        $imgHeight = $theme->getCfg('category/image_height') ? $theme->getCfg('category/image_height') : '';
        $showWishlist = $theme->getCfg('category_grid/display_addtowishlist');
        $showCompare = $theme->getCfg('category_grid/display_addtocompare');
        $showCart = $theme->getCfg('category_grid/display_addtocart');
        $showSize = $theme->getCfg('category_grid/display_size');
        $showPrice = $theme->getCfg('category_grid/display_price');
        $showColor = $theme->getCfg('category_grid/display_color');
        $showRating = $theme->getCfg('category_grid/display_rating');
        $showProductName = $theme->getCfg('category_grid/display_productname');
        $addtolinks_position = $theme->getCfg('category_grid/addtolinks_position');
        $_columnCount = $block->getData('product_m_w');

        $containerClasses = "{$viewMode} products-{$viewMode} products-grid-partitioned category-products-grid";
        $itemgridClasses = 'itemgrid zoo-itemgrid-adaptive';

        // Get number of columns (from parameter or from theme config)
        $columnCount = $_matoHelper->getCfg('category_grid/column_count');
        if(!isset($columnCount) || empty($columnCount) || !$columnCount) $columnCount = 3;
        $itemgridClasses .= " zoo-grid-{$columnCount}col";

        if ($_matoHelper->getCfg('category_grid/display_name_single_line'))
            $containerClasses .= ' zoo-single-line-name';
        if ($_matoHelper->getCfg('category_grid/hover_effect'))
            $containerClasses .= ' hover-effect';
        if ($_matoHelper->getCfg('category_grid/centered'))
            $containerClasses .= ' centered';
        if ($_matoHelper->getCfg('category_grid/enable_border_boxshadow'))
            $containerClasses .= ' enable_border_boxshadow';
        if ($_matoHelper->getCfg('category_grid/disable_border_radius'))
            $containerClasses .= ' disable_border_radius';
        ?>
        <div class="<?php /* @escapeNotVerified */  echo $containerClasses; ?>" id="<?php echo $_id; ?>">
            <ol class="clearfix items product-items itemgrid <?php /* @escapeNotVerified */
            echo $type; ?>  <?php if ($itemgridClasses) echo $itemgridClasses; ?>">
                <?php $i = 0;
                foreach ($items as $_item): ?>
                    <?php /* @escapeNotVerified */
                    echo '<!-- ' . $image . '-->' ?>
                    <?php $i++ ?>
                    <?php /* @escapeNotVerified */
                    if($_item->getIsSalable()) $product_stock = 'product-instock'; else $product_stock = 'product-oustock';
                    ?>
                    <li class="product-item product_hover <?php echo $product_stock ?>">
                        <div
                            class="product-item-info <?php if ($alternative_img = $theme->getAltImgHtml($_item, $imgWidth, $imgHeight, $image)): ?> have-alternative-image <?php endif; ?>"
                            data-container="product-grid">
                            <div class="zoo-inner-product-item-info">
                                <div class="zoo-product-image">
                                    <?php if ($_item->getIsSalable()): echo $_matoHelper->getLabel($_item); ?>
                                    <?php else : ?>
                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                echo __('Out of stock') ?></span></div>
                                    <?php endif; ?>
                                    <?php if ($addtolinks_position == 1): ?>
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist != 'remove'): ?>
                                            <div class="zoo-wishlist <?php echo 'product_'.$showWishlist.'_item'; ?>" data-role="add-to-links">
                                                <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                   data-action="add-to-wishlist"    title="">
                                                    <i class="fa fa-heart-o"></i>
                                                    <span class="tooltip"><?php /* @escapeNotVerified */     echo __('Add to wishlist') ?></span>
                                                </a>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($block->getAddToCompareUrl() && $showCompare != 'remove'): ?>
                                            <div class="zoo-compare <?php echo 'product_'.$showCompare.'_item'; ?>" data-role="add-to-links">
                                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                <a href="#" class="action tocompare"  data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item); ?>' >
                                                    <span class="cs-font clever-icon-compare-6"></span>
                                                    <span class="tooltip"><?php /* @escapeNotVerified */     echo __('Add to Compare') ?></span>
                                                </a>
                                            </div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <a href="<?php /* @escapeNotVerified */
                                    echo $block->getProductUrl($_item) ?>" class="product-item-photo" <?php if ($lazyload) echo 'style="min-height: '.$min_height_img_lazyload.'px"'?>>

                                        <?php if (!$imgWidth) : ?>
                                            <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                        <?php else: ?>
                                            <img id="product-collection-image-<?php echo $_item->getId(); ?>"
                                                <?php if($lazyload): ?>
                                                    class="clazyload"  data-src="<?php echo $_imageHelper->getImg($_item, $imgWidth, $imgHeight, 'category_page_grid'); ?>"
                                                    src="<?php echo $block->getViewFileUrl('CleverSoft_Base::images/transparent.gif'); ?>" width="auto" height="auto"
                                                <?php else: ?>
                                                    src="<?php echo $_imageHelper->getImg($_item, $imgWidth, $imgHeight, 'category_page_grid'); ?>"
                                                <?php endif; ?>
                                                 alt="<?php echo $block->stripTags($_item->getName(), null, true) ?>"/>
                                        <?php endif; ?>
                                        <?php if ($theme->getCfg('category/alt_image')): ?>
                                            <span class="product-img-additional alt-image">
                                 <?php echo $alternative_img; ?>
                            </span>
                                        <?php endif; ?>
                                    </a>

                                    <div class="options-slideup">
                                        <div class="zoo-quickview">
                                <span rel="tooltip" data-placement="top"
                                      class="btn-cart zoo-tooltip show-quickview"
                                      data-id="<?php echo $_item->getId(); ?>">
                                 <?php echo __('Quick view') ?></span>
                                            <a class="product-quickview"
                                               href="<?php echo $block->getUrl('quickview/product/view/id/' . $_item->getId()); ?>"
                                               data-id='quickview-<?php echo $_item->getId() ?>'
                                               style='display:none'><?php echo __('Quick view') ?></a>
                                        </div>
                                    </div>
                                    <div class="product-date"
                                         data-date="<?php echo $this->helper('CleverSoft\CleverProduct\Helper\Data')->getDate($_item) ?>"></div>
                                </div>

                                <div class="product details product-item-details">
                                    <?php if ($showProductName != 'remove'): ?>
                                        <h5 class="product-item-name <?php echo 'product_'.$showProductName.'_item'; ?>">
                                            <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                               href="<?php /* @escapeNotVerified */
                                               echo $block->getProductUrl($_item) ?>"
                                               class="product-item-link">
                                                <?php echo $block->escapeHtml($_item->getName()) ?>
                                            </a>
                                        </h5>
                                    <?php endif; ?>

                                    <?php if ($templateType && $showRating != 'remove'): ?>
                                        <div class="<?php echo 'product_'.$showRating.'_item'; ?>">
                                            <?php echo $block->getReviewsSummaryHtml($_item, $templateType, true) ?>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($showPrice != 'remove'): ?>
                                        <div class="<?php echo 'product_'.$showPrice.'_item'; ?>">
                                            <?php echo $block->getProductPriceHtml($_item, \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE); ?>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($showColor != 'remove'): ?>
                                        <div class="<?php echo 'product_'.$showColor.'_item'; ?>">
                                            <?php echo $block->getColorSwatchDetailsHtml($_item); ?>
                                        </div>
                                    <?php endif; ?>


                                    <div class="hover-area text-center">
                                        <?php if ($showCart != 'remove'): ?>
                                            <div class="actions-primary <?php echo 'product_'.$showCart.'_item'; ?>">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart"
                                                                data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */
                                                                echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                type="button">
                                                            <?php /* @escapeNotVerified */
                                                            echo __('Add to Cart') ?>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php if ($_item->isSaleable()): ?>
                                                            <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                            <form data-role="tocart-form"
                                                                  action="<?php /* @escapeNotVerified */
                                                                  echo $postParams['action']; ?>" method="post">
                                                                <input type="hidden" name="product"
                                                                       value="<?php /* @escapeNotVerified */
                                                                       echo $postParams['data']['product']; ?>">
                                                                <input type="hidden"
                                                                       name="<?php /* @escapeNotVerified */
                                                                       echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                                       value="<?php /* @escapeNotVerified */
                                                                       echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                                <?php echo $block->getBlockHtml('formkey') ?>
                                                                <button type="submit"
                                                                        class="action tocart">
											<span><?php /* @escapeNotVerified */
                                                echo __('Add to Cart') ?></span>
                                                                </button>
                                                            </form>
                                                        <?php else: ?>
                                                            <?php if ($_item->getIsSalable()): ?>
                                                                <div class="stock available">
											<span><?php /* @escapeNotVerified */
                                                echo __('In stock') ?></span></div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable">
											<span><?php /* @escapeNotVerified */
                                                echo __('Out of stock') ?></span></div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                <?php endif; ?>

                                                <?php if ($addtolinks_position == 0): ?>
                                                    <div class="add-to-links">
                                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist != 'remove'): ?>
                                                            <div class="<?php echo 'product_'.$showWishlist.'_item'; ?>" data-role="add-to-links">
                                                                <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                                   data-action="add-to-wishlist"    title="">
                                                                    <i class="fa fa-heart-o"></i>
                                                                    <span class="add-to-label"><?php /* @escapeNotVerified */     echo __('Wishlist') ?></span>
                                                                </a>
                                                            </div>
                                                        <?php endif; ?>
                                                        <?php if ($block->getAddToCompareUrl() && $showCompare != 'remove'): ?>
                                                            <div class="<?php echo 'product_'.$showCompare.'_item'; ?>" data-role="add-to-links">
                                                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                                <a href="#" class="action tocompare"  data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item); ?>' >
                                                                    <span class="cs-font clever-icon-compare-6"></span>
                                                                    <span class="add-to-label"><?php /* @escapeNotVerified */     echo __('Compare') ?></span>
                                                                </a>
                                                            </div>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach ?>
            </ol>
        </div>
        <?php if (!$block->isRedirectToCartEnabled()) : ?>
            <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }


    </script>
        <?php endif; ?>
        <script>
            require([
                "jquery"
            ],function($){
                $(window).load(function () {
                    window.gridLayout = function(id = null){
                        id = id ? id : '<?php echo $_id; ?>';
                        $('#'+id).attr('data-mage-init', JSON.stringify({'equalHeight': {'target': ' .product-item'}}));
                        $('#'+id).trigger('contentUpdated');
                    }
                });
            });
        </script>
        <?php if($this->helper('CleverSoft\Base\Helper\Data')->getCfg('category_grid/equal_height')): ?>
            <script type="text/x-magento-init">
    {
        "#<?php echo $_id ?>": {
            "equalHeight": {
                "target": " .product-item"
            }
        }
    }
</script>
        <?php endif;?>
    <?php }
    ?>
<?php endif ?>
