<?php
/**
 * @category    CleverSoft
 * @package     CleverBase
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
?>
<?php
$theme = $this->helper('CleverSoft\Base\Helper\Data');
$threshold = $theme->getCfg('responsive/threshold');
$config = $theme->getCfg('responsive/iconlazyload');
if (isset($config) and $config !='') {
    $image = $config;
    $om = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $om->create('Magento\Store\Model\StoreManagerInterface');
    $image_url = $storeManager->getStore()
            ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'lazyload/' . $image;
} else {
    $image_url = $block->getViewFileUrl('CleverSoft_Base::images/transparent.gif');
}
?>
<script>
    requirejs(['jquery', "js/jquery.noconflict",'jqueryLazyload'],function ($) {
        window.lazyloadfunction = function(event, container) {
            if ($(".clazyload").length > 0) {
                $(".clazyload").lazyload({
                    data_attribute: "src",
                    event : event,
                    container: container,
                    placeholder: '<?php echo $image_url;?>',
                    threshold: '<?php echo $threshold;?>',
                    failure_limit : 10
                });
            }
        };
        $(document).ready(function () {
            lazyloadfunction('scroll');
            $(document).bind('ajaxComplete', function(){
                lazyloadfunction('scroll');
            });
            /* carousel drag drop*/
            document.ondrag = function(event) {
                lazyloadfunction('ondrag');
            };
        });
    });
</script>